### ISSUE TITLE
fromList/toList confusingly named

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-maps#10]
These functions take and return arrays respectively. Shouldn't they be called `fromArray` and `toArray`?

**Comment by sharkdp** [comment]
I think this can be closed, since the types have changed in the newest version:
```purescript
toList :: forall k v. Map k v -> List (Tuple k v)
fromList :: forall k v. (Ord k) => List (Tuple k v) -> Map k v
```

**Comment by garyb** [comment]
:+1:
