### ISSUE TITLE
Version 3.5.0 is missing purescript-foldable-traversable dependency 

### ISSUE THREAD

**Issue by kenkku** [purescript/purescript-maps#119]
Hi,

The version released yesterday, which includes 9de5651d6319b68d2b2bfacc912a0078524caab6, added an implicit dependency of purescript-foldable-traversable 3.4.0. It uses `Data.FoldableWithIndex`, and some others, which does not exist in purescript-foldable-traversable until 3.4.0. This dependency is pulled in via `purescript-arrays`, but it only requires `^3.0.0` of purescript-foldable-traversable.

**Comment by hdgarrood** [comment]
Oops. Thanks for the report!
