### ISSUE TITLE
NonEmptyMap

### ISSUE THREAD

**Issue by matthewleon** [purescript/purescript-maps#141]
Would nice to have convenience functions for this.

**Comment by hdgarrood** [comment]
I’m not sure - this doesn’t seem to me as lobviously useful as non empty variants of some other types like NonEmptyList. Do you have some concrete use cases in mind?

**Comment by matthewleon** [comment]
Mostly, that if you get they `keys` or `values` of such a map, it can come out as a `NonEmptyArray` or whatever, which is nice.

**Comment by hdgarrood** [comment]
I think letting a separate library provide this is probably a good move, at least for now (especially now that one exists). Shall we close this?
