### ISSUE TITLE
Add IntMap

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-maps#15]
Like `StrMap` but backed by an array.

**Comment by tel** [comment]
I'm experimenting with a Patricia tree implementation at [tel/purescript-intmaps](https://github.com/tel/purescript-intmaps). Not suggesting that this should be included at all, but in the event that there's some feature requests to triage from here I'd be interested in seeing them.

**Comment by paf31** [comment]
A patricia tree probably makes a lot more sense, especially since we can implement strict and lazy variants, and it can deal with sparse data more efficiently.

**Comment by matthewleon** [comment]
any thoughts about merging the package in question in? Comments here https://github.com/tel/purescript-intmaps/pull/20 lead me to believe this may be welcome by @tel

**Comment by tel** [comment]
Feel free to grab it in. I'm not able to actively maintain intmaps nowadays as I'm not working in Purescript, but definitely feel free to pull things in.
