### ISSUE TITLE
StrMap for PureScript 0.12?

### ISSUE THREAD

**Issue by justinwoo** [purescript/purescript-maps#150]
Sorry if I missed the conclusion, but as we now have https://github.com/purescript/purescript-ordered-collections for various collections, can we now have a StrMap/"JSObject" package somewhere?

**Comment by justinwoo** [comment]
I guess it's in https://github.com/purescript/purescript-foreign-object now

**Comment by garyb** [comment]
Yes, sorry, I meant to point that out after Christoph released it the other day.
