### ISSUE TITLE
StrMap backing object inherits from Object.prototype and lookup uses in

### ISSUE THREAD

**Issue by michaelficarra** [purescript/purescript-maps#35]
I imagine `lookup` will think that keys like `"toString"` and `"hasOwnProperty"` exist in the object, even though the functions that rely on `Object.keys` or iteration through for-in won't see these properties because they're non-enumerable. I haven't tested this, but I'm pretty sure I'm right just by looking at the implementation.

**Comment by garyb** [comment]
Yeah, I'm pretty sure you're right too.

**Comment by michaelficarra** [comment]
There's two possible solutions:

0. use a `hasOwnProperty` test instead of `in`
0. use `Object.create(null)` as the backing object

I'd probably decide which to do based on performance. I'm going to guess the first option is better optimised in most implementations right now, but tests should be done to confirm.

**Comment by garyb** [comment]
Interesting, I wasn't aware of option 2 - I just assumed we'd have to use `hasOwnProperty`. You get a truly empty prototype with `Object.create(null)` then?

**Comment by michaelficarra** [comment]
Yep.

**Comment by michaelficarra** [comment]
@garyb is this fixed now after https://github.com/purescript/purescript-maps/commit/cca72e0a6ca577bf75ccb4641a333032e5120cbe#diff-f398949aafcfd55358d80eec690ee116?

**Comment by garyb** [comment]
Yes! (Although it also broke it, #39 fixed the new bug though) Thanks for the reminder.
